Added a list of products and styles for it
code-rock/react-store pull request #1
Opened 2020-12-03 11:56 UTC by code-rock

2020-12-07 07:50 UTC, CSSSR-School approved these changes

2020-12-07 15:23 UTC, vislogurov requested changes

2020-12-07 15:23 UTC, vislogurov commented on src/components/ProductTitle/ProductTitle.js
> +    return <h1 className='title'>{title}</h1>;
В целом такое решение тоже имеет место быть. Но, хорошей практикой в этом случае, будет использование пропса `children`. Такой поход позволяет более универсально передавать контент в компоненты:

```
<ProductTitle>
 // любой контент
</ProductTitle>
```

Дополнительно, такой подход открывает возможности для использования Children API https://reactjs.org/docs/react-api.html#reactchildren , когда нам нужно _что то _ сделать с чилдренами дополнительно

2020-12-07 15:23 UTC, vislogurov commented on src/index.js
> +        <div className='wrapper'>
Тут прямо напрашивается `main`

2020-12-07 15:23 UTC, vislogurov commented on src/components/ProductList/ProductList.js
> +              {products.map((el) =>  (
Нужно продумать UI на случай, если `products` не пришли вообще.

2020-12-07 18:08 UTC, vislogurov requested changes

2020-12-07 18:08 UTC, vislogurov commented on src/index.js
> +        <div className='main'>
Тут подразумевался вот этот `main` 
https://developer.mozilla.org/ru/docs/Web/HTML/Element/main )))

2020-12-07 19:21 UTC, code-rock commented on src/index.js
> +        <div className='main'>
оу, точно! Спасибо) 
Я приложила фото, чтобы было понятнее.. Цены жирненькие и слиплись..  или надо было прокинуть уже красивые через props??
``
![image](https://user-images.githubusercontent.com/61647612/101394582-cb039380-38d9-11eb-8d01-46fa9a160ed1.png)

2020-12-08 06:59 UTC, vislogurov approved these changes

2020-12-08 08:08 UTC, merged