Filter and logger
code-rock/react-store pull request #3
Opened 2020-12-16 09:02 UTC by code-rock

2020-12-16 09:40 UTC, vislogurov requested changes

2020-12-16 09:40 UTC, vislogurov commented on src/containers/ProductPage.js
> +            this.setState({ errorFieldFrom: true });
Кажется это можно объединить в один setState

2020-12-16 09:40 UTC, vislogurov commented on src/containers/ProductPage.js
> +        if (!Array.isArray(products) && !products.length) return [0,0];
`if (cond) doSomething` это визуальный антипаттерн написания кода. На этом месте упадёт любой современный линтер.
Нужно все условия привести к виду 
```
if (cond) {
  doSomething()
}
```

2020-12-16 09:40 UTC, vislogurov commented on src/containers/ProductPage.js
> +        this.handleButtonClick = this.handleButtonClick.bind(this);
Можно не биндить, а заюзать стрелочную функцию. Тогда уйдёт лишний "мусор" из конструктора

2020-12-16 09:40 UTC, vislogurov commented on src/components/RangeFilter/RangeFilter.js
> +        return <div className="filter">
Чёт слишко жёсткая "универсализация"))))
Нельзя ли к такому виду привести:
```
                 <Title>Цена</Title>
                <div className={s.filterRow}>
                    <div className={s.filterItem}>
                        от <input type="text" defaultValue={minPrice} ref={this.filterMinPrice}/>
                    </div>
                    <div className={s.filterItem}>
                        до <input type="text" defaultValue={maxPrice} ref={this.filterMaxPrice}/>
                    </div>
                </div>
                <button type="submit" className={s.filterSubmit}><span>Применить</span></button>
               ```
               Что то типа такого?

2020-12-16 09:40 UTC, vislogurov commented on src/containers/ProductPage.js
> +                <RangeFilter
Можно сделать один "глупый" компонент инпута и внутри него уже в зависимости от переданных пропсов визуализировать его состояния: error, success, disabled. А шириной управлять через обёртки-родителей.

Это будет "тру"-универсализация)

2020-12-16 09:40 UTC, vislogurov commented on src/components/RangeFilter/RangeFilter.js
> +        return <div className="filter">
Если это инпуты, то где форма, которая примет их данные?

2020-12-16 09:51 UTC, vislogurov commented on src/components/RangeFilter/RangeFilter.js
> +        return <div className="filter">
Дополнительно https://developer.mozilla.org/ru/docs/Web/HTML/Element/fieldset в помощь

2020-12-16 12:53 UTC, code-rock commented on src/containers/ProductPage.js
> +        this.handleButtonClick = this.handleButtonClick.bind(this);
![image](https://user-images.githubusercontent.com/61647612/102350795-84d3c180-3fb6-11eb-9a0e-72e23356ce1c.png)
в видосе мужичек говорит, что это устаревший вариант и могут быть проблемы с производительностью.. подозрительно все это

2020-12-16 13:04 UTC, vislogurov commented on src/containers/ProductPage.js
> +        this.handleButtonClick = this.handleButtonClick.bind(this);
Могут быть. Доли наносекунд) Но зато у тебя 3 дополнительных символа против 100500 в методе с байндом. Если методов много, то визуально компонент становится "тяжелее". А с твоим компонентом будут работать люди, в этом случае лучше сделать уклон в human-readable, чем в performance.

Ну и в видосе ты ссылаешь на стрелки в рендере, а говорю, что стрелки в объявлении метода нужны)

2020-12-16 13:06 UTC, code-rock commented on src/containers/ProductPage.js
> +        this.handleButtonClick = this.handleButtonClick.bind(this);
а ..ок

2020-12-17 11:08 UTC, vislogurov approved these changes

2020-12-17 11:08 UTC, vislogurov commented on src/containers/ProductPage.js
> +            this.setState({ errorFrom: true, errorType: 'sp'});
Что такое `sp` и 'np'? Это должно быть очевидно другому человеку, читающему твой код. Если такой нейминг критически необходим, то оставляй коммент почему

2020-12-17 11:08 UTC, vislogurov commented on src/components/ProductPriсe/ProductPriсe.js
> +function disaggregation(str = '', n = 3) {
Что если диссагрегация понадобится в другом компоненте? Будешь копипастить. Всякие утилитарные функции (напрямую не относящиеся к логике компонента) предлагаю вынести в отдельную папку utils.

2020-12-17 12:58 UTC, code-rock commented on src/containers/ProductPage.js
> +            this.setState({ errorFrom: true, errorType: 'sp'});
скорее нет : )

2020-12-17 12:58 UTC, merged