Add discount
code-rock/react-store pull request #4
Opened 2020-12-22 09:16 UTC by code-rock

2020-12-22 09:45 UTC, vislogurov requested changes

2020-12-22 09:45 UTC, vislogurov commented on src/components/DiscountFilter/DiscountFilter.js
> +        const Input = withState(InputNumber);
В таком варианте каждый рендер у тебя будет создаваться новый инстанс InputNumber. Соответсвенно shallow-compare тут вернёт false и всё поддерево перерендирится, хотя явных причин для этого нет.

Тут либо выносить оборачивание в ХОК за рендер....

2020-12-22 09:45 UTC, vislogurov commented on src/components/DiscountFilter/DiscountFilter.js
> +export default DiscountFilter;
...либо оборачивать в ХОК на этапе экспорта

2020-12-22 09:45 UTC, vislogurov commented on src/components/InputNumber/InputNumber.js
> +        return <input className="filter__input"
Если это "элемент" по БЭМу, то почему он в отдельный файл вынесен?
Тут более уместным был бы класс "input", а вот уже на этапе сборке фильтра из инпутов, каждый из инпутов можно обернуть в "filter__input", тогда сохранится иерархия "блок -> элмент"

2020-12-22 09:45 UTC, vislogurov commented on src/containers/ProductPage.js
> +        const { pricemin, pricemax, discount } = {...this.state, [id]: value};
Не избыточно ли тут копию стейта делать `...this.state`? Ты ведь не мутируешь `pricemin, pricemax, discount`, а просто читаешь их.

2020-12-22 09:45 UTC, vislogurov commented on src/containers/WithState.js
> +            return <HoccedComponent onChange={this.handleChange}
Есть гарантии, что хокнутый компонент юзает конечный набор только этих пропсов `onKeyDown, value, id, min`?  В уроке есть упоминание о потере пропсов и о том откуда берётся `...this.props` в ХОКах

2020-12-22 10:11 UTC, vislogurov commented on src/components/DiscountFilter/DiscountFilter.js
> +        const Input = withState(InputNumber);
Правило: нужно делать рендер, как можно "тоньше"

2020-12-22 13:49 UTC, code-rock commented on src/containers/ProductPage.js
> +        const { pricemin, pricemax, discount } = {...this.state, [id]: value};
не совсем.. функция срабатывает когда изменяется одно из состояний, это было сделано чтобы не думать какое именно.. а setState вызывался в конце функции один раз, и для списка товаров и для этого свойства

2020-12-22 15:11 UTC, vislogurov requested changes

2020-12-22 15:11 UTC, vislogurov commented on src/containers/WithState.js
> +export default function withState(HoccedComponent){
Давай поменяем HoccedComponent на InputCompoment. "Hocced" в тексте урока был добавлен, чтобы было более очевидно, что с целевым компонентом _что-то_  делается извне.

Тут же, судя по коду, становится понятно, что это ХОК будет вешаться только на инпуты. Больше конкретики для  читающего вносим.

2020-12-22 15:11 UTC, vislogurov commented on src/containers/ProductPage.js
> +        const { pricemin, pricemax, discount } = {...this.state, [id]: value};
Ок. Метод получился слишком большой. Сложно отдебажить, потому что они делает несколько вещей. Предлагаю разбить его на два:
1) Один будет `handleFilterForm = (name, value) => this.setState(state => ({ ...state, [name]: value }))` отвечать непосредственно за изменение стейта
2) А другой будет возвращать список отфильтрованных продуктов 
```
getProducts = () => {
		const { minPrice, maxPrice, discount } = this.state
		return data.filter(......)
	}
```

2020-12-22 15:11 UTC, vislogurov commented on src/containers/ProductPage.js
> +    isDiscount = (withSale, beforeSale, discount) => {
`is`-утилитки положи рядом в файл util, по названию понятно, что они проверяют. Необязятельно их исходники видеть прямо в компоненте

2020-12-22 15:11 UTC, vislogurov commented on src/containers/WithState.js
> +export default function withState(HoccedComponent){
`src/containers` это не контейнер, если мы будет оперировать терминами реакта. Контейнер более глобальные части стейта приложения сдержит. Здесь же стейт точечный, как раз то, за что отвечают ХОКи. Перенеси его в папку `/hocs/`, чтобы при импорте было понятно, что это не просто компонент, а ХОК.

2020-12-22 15:11 UTC, vislogurov commented on src/components/DiscountFilter/DiscountFilter.js
> +export default DiscountFilter;
Если коммент поправлен, то пиши плз "done", или закрывай его.

2020-12-22 15:41 UTC, code-rock commented on src/components/DiscountFilter/DiscountFilter.js
> +export default DiscountFilter;
ок

2020-12-23 06:45 UTC, vislogurov commented on src/hocs/WithState.js
> +            return <InputCompoment {...this.props}
В случае ХОКа так ок, но в целом `{...this.props}` нужно писать в самом конце. Иначе есть риск "перезатереть" пропсы.

2020-12-23 06:45 UTC, vislogurov approved these changes

2020-12-23 07:01 UTC, merged