Add redux
code-rock/react-store pull request #6
Opened 2020-12-28 09:36 UTC by code-rock

2020-12-28 09:55 UTC, vislogurov requested changes

2020-12-28 09:55 UTC, vislogurov commented on src/app/containers/ProductPage.js
> +        store.subscribe(() => {
"Подключи react-redux, переделай подписки на connect, контейнеры вынеси в отдельные файлы, а чистые файлы(глупые компоненты) в pure." Предлагаю сразу перейти к этой части из задания. Сейчас у тебя более низкоуровневая реализация, "оторванная" от боевого применения redux в связке с реактом.

2020-12-29 07:13 UTC, vislogurov requested changes

2020-12-29 07:13 UTC, vislogurov commented on src/app/containers/ProductPage/ProductPageConnect.js
> +        this.props.changePriceMin(this.prices.min);
Можно же просто сдиспатчить экшен типа "CLEAR_FORM" и на его основе просто вернуть initialState. И всё, и не придётся тогда каждый фильтр менять точечно.

2020-12-29 10:31 UTC, code-rock commented on src/app/containers/ProductPage/ProductPageConnect.js
> +        this.props.changePriceMin(this.prices.min);
Гениально)

2020-12-30 10:41 UTC, vislogurov approved these changes

2021-01-01 08:14 UTC, merged