Redux modularization
code-rock/react-store pull request #7
Opened 2021-01-23 19:01 UTC by code-rock

2021-01-25 11:43 UTC, vislogurov requested changes

2021-01-25 11:43 UTC, vislogurov commented on src/app/components/CategoryButton/index.js
> +import { connect } from 'react-redux';
Концептуально это "контейнер", тк идёт работа со стором. Контейнеры должны выноситься в директорию `containers`. Это принятый стандарт, иначе будет нарушаться SRP. Это касается всех "контейнеров".

В уроке про "умные/глупые" компоненты есть раздел структура папок. И в целом так описано, какие профиты от такого разделения есть.

2021-01-25 11:43 UTC, vislogurov commented on src/app/components/Pagination/Pagination.js
> +        return this.isShort(max)       ? this.createLinks(1, max, active)
Это никуда не годится. Область применения тернарника — максимум одно условие. Дальше уже у читающего такой код в голове простыня из условию начнёт строиться((

Как понять что и когда вернёт этот метод? Много условий? Заюзай switch, он как раз для таких случаев и существует в языке.

2021-01-25 11:43 UTC, vislogurov commented on src/app/components/Pagination/Pagination.js
> +        let pages = [];
Инфа о pages же уже лежит в сторе, почему бы не брать её оттуда?

2021-01-25 11:43 UTC, vislogurov commented on src/app/store/selectors.js
> +import getProducts from '../utils/getProducts';
Если это селектор, то за счёт чего происходит мемоизация?

2021-01-25 11:43 UTC, vislogurov commented on src/app/store/selectors.js
> +import getProducts from '../utils/getProducts';
"Для селекторов используй reselect и т.д. Преобразую фунцию для разбиения продуктов на страницы в селектор." Я про эту часть ТЗ.

2021-01-31 17:06 UTC, code-rock commented on src/app/components/Pagination/Pagination.js
> +        let pages = [];
Это разметка видимых страниц пагинации

2021-02-02 10:25 UTC, vislogurov requested changes

2021-02-02 10:25 UTC, vislogurov commented on src/app/components/Pagination/Pagination.js
> +                    {activePage !== 1 ? this.renderLink((activePage - 1), activePage, 'Назад'): ''}
Ты либо рендеришь кнопку, либо ничего не рендеришь. От этого скачет вёрстка на бою:
http://s.csssr.ru/U0FMPH83W/20210202132125.mp4

Рендери кнопки "Назад/Вперёд" всегда, но делай их disabled по достижению начала/конца. Вешай на них  `.disabled` стиль, делающий их прозрачными и без возможности кликнуть (pointer-events:none)

2021-02-03 13:32 UTC, vislogurov approved these changes

2021-03-12 08:04 UTC, vislogurov requested changes

2021-03-12 08:04 UTC, vislogurov commented on src/app/components/Pagination/Link.js
> +export function WithNumberLink({ currPage, urlPage }) {
`with` приставка заставит читающего думать, что это HOC, хотя это не так. Почему бы не сделать просто Number/TextLIink?

2021-03-12 08:04 UTC, vislogurov commented on src/app/components/Pagination/index.js
> +function fillRangeOfValues(start, end) {
C 31й по 56ю строку объявленные функции не относятся напрямую к функционалу пагинации и носят утилитарный характер. Их нужно вынести в utlis, код станет яснее и читабельнее.

2021-03-12 08:04 UTC, vislogurov commented on src/app/components/ProductCard/ProductCardWrapper.js
> +function range(to) {
Чем это отличается от fillRangeOfValues в пагинации?

2021-03-12 08:04 UTC, vislogurov commented on src/app/components/ProductCard/ProductCardWrapper.js
> +function range(to) {
Чем это отличается от fillRangeOfValues в пагинации?

2021-03-12 08:04 UTC, vislogurov commented on src/app/components/ProductList/ProductListWrapper.js
> +      if (maxPage < page) deletePropertyFromUrl('pageNum', history);
Условие должно явно выделяться среди остального кода. Сейчас оно теряется на фоне строк.
Приведи его к классическому виду со скобками, переносом строку и явным return'ом

2021-03-15 15:37 UTC, vislogurov approved these changes

2021-03-15 17:57 UTC, merged